import numpy as np
import warnings
from sklearn.utils import check_random_state
from sklearn.neighbors import NearestNeighbors
from imblearn.over_sampling.base import BaseOverSampler

class DROS(BaseOverSampler):
    """
    A Robust Oversampling Approach for Class Imbalance Problem With Small Disjuncts (DROS)
    
    Parameters
    ----------
    sampling_strategy : float, str, dict or callable, default='auto'
        Sampling information to resample the data set.
    random_state : int, RandomState instance, default=None
        Control the randomization of the algorithm.
    K_Maj : int, default=7
        The number of nearest majority samples to consider.
    project1 : float, default=-0.7660
        The threshold for projection value in finding relative minority samples.
    cAngle : float, default=0.5
        The central angle constraint for searchlight structures.
    g : float, default=1.0
        The minimum scale constraint for sampling radius.
    """
    
    def __init__(self, sampling_strategy="auto", random_state=None, 
                 K_Maj=7, project1=-0.7660, cAngle=0.5, g=1.0):
        super().__init__(sampling_strategy=sampling_strategy)
        self.random_state = random_state
        self.K_Maj = K_Maj
        self.project1 = project1
        self.cAngle = cAngle
        self.g = g

    def _fit_resample(self, X, y):
        self.random_state_ = check_random_state(self.random_state)
        
        classes, class_counts = np.unique(y, return_counts=True)
        maj_class = classes[np.argmax(class_counts)]
        
        X_resampled = X.copy()
        y_resampled = y.copy()
        
        for min_class in classes:
            if min_class == maj_class:
                continue
                
            minority_indices = np.flatnonzero(y == min_class)
            majority_indices = np.flatnonzero(y == maj_class)
            trainMinority = X[minority_indices]
            trainMajority = X[majority_indices]
            
            # Calculate NNG (number of new samples to generate)
            if isinstance(self.sampling_strategy_, dict) and min_class in self.sampling_strategy_:
                NNG = self.sampling_strategy_[min_class] - len(minority_indices)
            else:
                # If strategy is 'auto' and sampling_strategy_ doesn't have it, default to matching majority
                NNG = len(majority_indices) - len(minority_indices)
                
            if NNG <= 0:
                continue
                
            trainMinorityResamplingNNG = self._area_resampling_DROS(
                trainMinority, trainMajority, NNG, self.random_state_)
                
            if trainMinorityResamplingNNG is None or len(trainMinorityResamplingNNG) == 0:
                warnings.warn(f"No samples were generated by DROS for class {min_class}.")
                continue
                
            X_resampled = np.vstack((X_resampled, trainMinorityResamplingNNG))
            y_resampled = np.hstack((y_resampled, np.full(len(trainMinorityResamplingNNG), min_class)))
            
        return X_resampled, y_resampled

    def _area_resampling_DROS(self, trainMinority, trainMajority, NNG, random_state):
        N_min, dim = trainMinority.shape
        K_Maj = min(self.K_Maj, trainMajority.shape[0])
        
        # step 1 distance computation and sorting
        nn = NearestNeighbors(n_neighbors=K_Maj, metric='euclidean').fit(trainMajority)
        distances, I_sortdistMinToMaj = nn.kneighbors(trainMinority)
        
        barrierKMaj = trainMajority
        chosedMajRM = trainMajority

        # step 2 relationship computation
        RMatrix = np.zeros((N_min, N_min))
        
        for i in range(N_min):
            iMin = trainMinority[i]
            RMinIndex = np.arange(i + 1, N_min)
            if len(RMinIndex) == 0:
                break
                
            remainedMin = trainMinority[RMinIndex]
            
            drectioniMinTochosedMajRM = -(chosedMajRM - iMin)
            norm = np.linalg.norm(drectioniMinTochosedMajRM, axis=1, keepdims=True)
            norm[norm == 0] = 1 
            drectioniMinTochosedMajRMNorm = drectioniMinTochosedMajRM / norm
            
            drectioniRMinTochosedMajRM = -(chosedMajRM[np.newaxis, :, :] - remainedMin[:, np.newaxis, :])
            norm_RMin = np.linalg.norm(drectioniRMinTochosedMajRM, axis=2, keepdims=True)
            norm_RMin[norm_RMin == 0] = 1
            drectioniRMinTochosedMajRMNorm = drectioniRMinTochosedMajRM / norm_RMin
            
            # Element-wise dot & extract min
            project = np.sum(drectioniMinTochosedMajRMNorm[np.newaxis, :, :] * drectioniRMinTochosedMajRMNorm, axis=2)
            minValue = np.min(project, axis=1) 
            
            pindex = np.where(minValue >= self.project1)[0]
            if len(pindex) > 0:
                valid_idx = RMinIndex[pindex]
                RMatrix[i, valid_idx] = 1
                RMatrix[valid_idx, i] = 1
                
        # step 3-5 searchlight scanning structure of each minority sample
        cellInf_list = []
        N_nonoise = 0
        
        for i in range(N_min):
            iMin = trainMinority[i]
            irelIndex = np.where(RMatrix[i, :] == 1)[0]
            if len(irelIndex) == 0:
                continue
                
            irelMin = trainMinority[irelIndex]
            
            nnKMaj = trainMajority[I_sortdistMinToMaj[i, :K_Maj]]
            meannnKMaj = np.mean(nnKMaj, axis=0)
            
            iMinMinusmeannnKMaj = iMin - meannnKMaj
            norm_i = np.linalg.norm(iMinMinusmeannnKMaj)
            if norm_i == 0:
                iMinMinusmeannnKMajNorm = np.zeros(dim)
            else:
                iMinMinusmeannnKMajNorm = iMinMinusmeannnKMaj / norm_i
                
            irelMinMinusiMin = irelMin - iMin
            projects = np.dot(irelMinMinusiMin, iMinMinusmeannnKMajNorm)
            projectsPos01 = projects > 0
            
            if np.sum(projectsPos01) > 0:
                meanlength = np.sum(projects[projectsPos01]) / np.sum(projectsPos01)
            else:
                meanlength = 0
                
            CircleCenter = meanlength * iMinMinusmeannnKMajNorm + iMin
            
            referedDirection = -iMinMinusmeannnKMajNorm
            BarKMajMinuscirCenter = barrierKMaj - CircleCenter
            norm_b = np.linalg.norm(BarKMajMinuscirCenter, axis=1, keepdims=True)
            norm_b[norm_b == 0] = 1
            BarKMajMinuscirCenterNorm = BarKMajMinuscirCenter / norm_b
            
            projectSD = np.dot(BarKMajMinuscirCenterNorm, referedDirection)
            sdbKMajIndex = projectSD >= self.cAngle
            fallInScannedAreaMaj = barrierKMaj[sdbKMajIndex]
            
            distimin = np.linalg.norm(iMin - CircleCenter)
            if len(fallInScannedAreaMaj) == 0:
                continue
                
            distTofallInScannedAreaMaj = np.linalg.norm(fallInScannedAreaMaj - CircleCenter, axis=1)
            mindist = np.min(distTofallInScannedAreaMaj)
            radius = min(distimin, mindist) + 0.5 * (mindist - distimin)
            
            if radius <= 0:
                continue
            if np.sum(np.abs(referedDirection)) == 0:
                continue
                
            N_nonoise += 1
            cellInf_list.append({
                'radius': radius,
                'cAngle': self.cAngle,
                'CircleCenter': CircleCenter,
                'referedDirection': referedDirection
            })
            
        if N_nonoise == 0:
            return np.array([])
            
        overGSDN = 0
        NForOnce = int(np.ceil(NNG / N_nonoise))
        trainMinorityResampling = []
        
        for i in range(N_nonoise):
            cell = cellInf_list[i]
            radius = cell['radius']
            cAngle = cell['cAngle']
            CircleCenter = cell['CircleCenter']
            referedDirection = cell['referedDirection']
            
            # length scale between [g, 1] relative to radius
            randomLength = (random_state.rand(NForOnce) * (1 - self.g) + self.g) * radius
            aRNorm = self._randm_direction_for_LAO(cAngle, referedDirection, NForOnce, dim, random_state)
            
            if len(aRNorm) == 0:
                continue

            chosedaRNorm = aRNorm[:NForOnce]
            if len(chosedaRNorm) < NForOnce:
                indices = random_state.choice(len(chosedaRNorm), NForOnce, replace=True)
                chosedaRNorm = chosedaRNorm[indices]

            chosedNewPoints = randomLength[:, np.newaxis] * chosedaRNorm + CircleCenter
            trainMinorityResampling.extend(chosedNewPoints)
            
        trainMinorityResampling = np.array(trainMinorityResampling)
        if len(trainMinorityResampling) > NNG:
            indices = random_state.permutation(len(trainMinorityResampling))[:NNG]
            trainMinorityResamplingNNG = trainMinorityResampling[indices]
        else:
            trainMinorityResamplingNNG = trainMinorityResampling
            
        return trainMinorityResamplingNNG

    def _randm_direction_for_LAO(self, CentralAngle, NormDirectionFromCCToimin, randNumEachTime, dim, random_state):
        randForOneNew = 100
        limitMaxCentralAngle = 0.99
        
        if CentralAngle >= 0.99:
            return np.tile(NormDirectionFromCCToimin, (randNumEachTime, 1))
            
        randDirection = random_state.randint(1, 101, size=(randForOneNew * randNumEachTime, dim)) - 50.0
        norm_r = np.linalg.norm(randDirection, axis=1, keepdims=True)
        norm_r[norm_r == 0] = 1
        aRNorm = randDirection / norm_r
        
        project_i_aR = np.dot(aRNorm, NormDirectionFromCCToimin)
        maxProject = np.max(project_i_aR)
        
        selectedRandDirection = []
        conditionIndex = np.where(project_i_aR >= CentralAngle)[0]
        if len(conditionIndex) > 0:
            selectedRandDirection.extend(aRNorm[conditionIndex])
            
        count2 = 0
        while maxProject < limitMaxCentralAngle and count2 < 50:
            count2 += 1
            randDirection = aRNorm + 1.0 * np.tile(NormDirectionFromCCToimin, (randForOneNew * randNumEachTime, 1))
            norm_r = np.linalg.norm(randDirection, axis=1, keepdims=True)
            norm_r[norm_r == 0] = 1
            aRNorm = randDirection / norm_r
            
            project_i_aR = np.dot(aRNorm, NormDirectionFromCCToimin)
            maxProject = np.max(project_i_aR)
            conditionIndex = np.where(project_i_aR >= CentralAngle)[0]
            if len(conditionIndex) > 0:
                selectedRandDirection.extend(aRNorm[conditionIndex])
                
        if len(selectedRandDirection) == 0:
            return np.array([])
            
        selectedRandDirection = np.array(selectedRandDirection)
        project_i_aR = np.dot(selectedRandDirection, NormDirectionFromCCToimin)
        
        indexV = []
        for v in range(10):
            lb = v * 0.1
            ub = (v + 1) * 0.1
            idx = np.where((project_i_aR > lb) & (project_i_aR <= ub))[0]
            indexV.append(idx)
            
        sizeV = [len(idx) for idx in indexV]
        Non0Ind = [i for i, size in enumerate(sizeV) if size > 0]
        if len(Non0Ind) == 0:
            return selectedRandDirection
            
        minSizeNon0 = min([sizeV[i] for i in Non0Ind])
        
        finalIndex = []
        for ii in Non0Ind:
            idx = indexV[ii]
            np.random.shuffle(idx)
            finalIndex.extend(idx[:minSizeNon0])
            
        secondSelectedRandDirection = selectedRandDirection[finalIndex]
        
        selectedSize = len(secondSelectedRandDirection)
        finalSize = min(selectedSize, randForOneNew * randNumEachTime)
        randpermD = random_state.permutation(selectedSize)
        finalRandDirection = secondSelectedRandDirection[randpermD[:finalSize]]
        
        return finalRandDirection
